[package]
name = "pardon"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.29"

[dev-dependencies]
num-bigint = "0.4.3"
proptest = "1.0.0"
proptest-derive = "0.3.0"
